apiVersion : apps/v1
kind: Deployment
metadata:
  name: cyberkabilangular 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cyberkabilangular
  template:
    metadata:
      labels:
        app: cyberkabilangular 
    spec:
      containers:
        - name: cyberkabilangular 
          image: paasrepoprod.azurecr.io/cyberkabilangular
          ports:
          - containerPort: 80